#!/bin/bash

RESOLV_CONF=/etc/resolv.conf
if ! [[ -f ${RESOLV_CONF} ]]; then
   cat > ${RESOLV_CONF} << 'EOF'
# Generated by show_dns.sh
nameserver 8.8.8.8
nameserver 1.1.1.1
nameserver 9.9.9.9
EOF
   echo Added ${RESOLV_CONF}
fi

is_packet_not_installed(){
   instaled=`dpkg-query -l ${1} 2>/dev/null | grep ${1}|awk -F ' ' '{print $1}'`
   #echo 1=${1} instaled=${instaled}
   if [[ ${instaled} == "ii" ]]; then
      return 1
   fi
}

is_packet_not_installed dnsutils && apt-get install -q -y dnsutils >/dev/null 2>&1

nmcli dev show | grep -e "TYPE\|DNS"
echo =======================
cat ${RESOLV_CONF}
echo =======================
if type nslookup >/dev/null 2>&1; then
   echo nslookup servers.onocoy.com
   nslookup servers.onocoy.com
elif type dig >/dev/null 2>&1; then
   echo dig servers.onocoy.com
   dig servers.onocoy.com
elif type getent >/dev/null 2>&1; then
   echo getent servers.onocoy.com
   getent servers.onocoy.com
elif type host >/dev/null 2>&1; then
   echo host -t A servers.onocoy.com
   host -t A servers.onocoy.com
fi

if [[ ${1} == "-s" ]]; then
   exit 254
fi
